# Use official GCC image
FROM gcc:latest

# Set working directory
WORKDIR /code

# Set default command
CMD ["g++", "main.cpp", "-o", "main", "&&", "./main"]



# docker build -t solanki018/cpp-runner ./cpp-runner
